FROM httpd:2.4

COPY ./lala.conf /usr/local/apache2/conf/httpd.conf

#RUN echo LoadModule proxy_module modules/mod_proxy.so >> /usr/local/apache2/conf/httpd.conf
#RUN echo LoadModule proxy_http_module modules/mod_proxy_http.so >> /usr/local/apache2/conf/httpd.conf

#RUN echo ProxyPass / http://wiki/ >> /usr/local/apache2/conf/httpd.conf
#RUN echo ProxyPassReverse / http://wiki/ >> /usr/local/apache2/conf/httpd.conf

#RUN echo ProxyPass / http://eibriel/ >> /usr/local/apache2/conf/httpd.conf
#RUN echo ProxyPassReverse / http://eibriel/ >> /usr/local/apache2/conf/httpd.conf
